# from app import db

# LOCATIONS =[
#     {
#       "SITE_ID": "0101014",
#       "SITE_NAME": "SACO TANNERY WASTE PITS",
#       "SITE_STRT_ADRS1": "FLAG POND RD",
#       "SITE_CITY_NAME": "SACO",
#       "SITE_STATE": "ME",
#       "SITE_ZIP_CODE": "04072",
#       "SITE_CONG_DISTRICT": "01",
#       "SITE_CNTY_NAME": "YORK",
#       "LATITUDE": 43.56055,
#       "LONGITUDE": -70.426389,
#       "NPL": "Deleted from the Final NPL",
#     },
#     {
#       "SITE_ID": "0101027",
#       "SITE_EPA_ID": "MED980524078",
#       "SITE_NAME": "MCKIN CO.",
#       "SITE_STRT_ADRS1": "MAYALL RD",
#       "SITE_CITY_NAME": "GRAY",
#       "SITE_STATE": "ME",
#       "SITE_ZIP_CODE": "04039",
#       "SITE_CONG_DISTRICT": "01",
#       "SITE_CNTY_NAME": "CUMBERLAND",
#       "SITE_FIPS_CODE": 23005,
#       "LATITUDE": 43.8841,
#       "LONGITUDE": -70.2942,
#       "NPL": "Currently on the Final NPL",
#     },
#     {
#       "SITE_ID": "0101028",
#       "SITE_EPA_ID": "MED980524128",
#       "SITE_NAME": "CALLAHAN MINING CORP",
#       "SITE_STRT_ADRS1": "HARBORSIDE",
#       "SITE_CITY_NAME": "BROOKSVILLE (CAPE ROSIER)",
#       "SITE_STATE": "ME",
#       "SITE_ZIP_CODE": "04617",
#       "SITE_CONG_DISTRICT": "02",
#       "SITE_CNTY_NAME": "HANCOCK",
#       "SITE_FIPS_CODE": 23009,
#       "LATITUDE": 44.351639,
#       "LONGITUDE": -68.810139,
#       "NPL": "Currently on the Final NPL",
#     },
#     {
#       "SITE_ID": "0101031",
#       "SITE_EPA_ID": "MED980731475",
#       "SITE_NAME": "O%27CONNOR CO.",
#       "SITE_STRT_ADRS1": "EASTERN AVE, RT 17",
#       "SITE_CITY_NAME": "AUGUSTA",
#       "SITE_STATE": "ME",
#       "SITE_ZIP_CODE": "04330",
#       "SITE_CONG_DISTRICT": "01",
#       "SITE_CNTY_NAME": "KENNEBEC",
#       "SITE_FIPS_CODE": 23011,
#       "LATITUDE": 44.301916,
#       "LONGITUDE": -69.736944,
#       "NPL": "Deleted from the Final NPL",
#     },
#     {
#       "SITE_ID": "0101036",
#       "SITE_EPA_ID": "MED980732291",
#       "SITE_NAME": "PINETTE%27S SALVAGE YARD",
#       "SITE_STRT_ADRS1": "GARDNER CREEK RD",
#       "SITE_CITY_NAME": "WASHBURN",
#       "SITE_STATE": "ME",
#       "SITE_ZIP_CODE": "04786",
#       "SITE_CONG_DISTRICT": "02",
#       "SITE_CNTY_NAME": "AROOSTOOK",
#       "SITE_FIPS_CODE": 23003,
#       "LATITUDE": 46.7782,
#       "LONGITUDE": -68.1701,
#       "NPL": "Deleted from the Final NPL",
#     }
# ]
# with app.app_context():
#     db.session.add_all(LOCATIONS)
#     db.session.commit()
