"""adds Superfund_site model

Revision ID: a423d289fdbf
Revises: 
Create Date: 2023-01-30 21:03:21.802715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a423d289fdbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superfund_site',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('site_strt_adrs1', sa.String(), nullable=True),
    sa.Column('site_city_name', sa.String(), nullable=True),
    sa.Column('site_state', sa.String(), nullable=True),
    sa.Column('site_zip_code', sa.String(), nullable=True),
    sa.Column('site_cong_district', sa.String(), nullable=True),
    sa.Column('site_cnty_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('npl', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('superfund_site')
    # ### end Alembic commands ###
